name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ssh ${{ secrets.USER }}@${{ secrets.HOST_IP }} """
          cd /var
          touch test.txt
          echo blablabla > test.txt
          cat test.txt
          """
